name: Deploy Laravel to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/u376682195/domains/edutorium.in
            git clone https://github.com/ahmakbardev/edutorium_new.git
            cd /home/u376682195/domains/edutorium.in/edutorium_new
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            git pull
            source ~/.bash_profile
            which composer
            composer --version
            composer install
            composer update
            php artisan key:generate
            php artisan route:clear
            php artisan config:cache
            php artisan optimize
            
            # Set permissions for storage directory
            find /home/u376682195/domains/edutorium.in/edutorium_new/storage -type d -exec chmod 755 {} \;
            find /home/u376682195/domains/edutorium.in/edutorium_new/storage -type f -exec chmod 644 {} \;
            
            rm -rf /home/u376682195/domains/edutorium.in/public_html/staging
            ln -s /home/u376682195/domains/edutorium.in/edutorium_new/public /home/u376682195/domains/edutorium.in/public_html/staging
